
test-warnings: false

disable:
  - prospector_N801
  - prospector_N802
  - prospector_N806

pep8:
  full: true
  disable:
    - N801
    - N802
    - N806

prospector:
  disable:
    - N801
    - N802
    - N806

