language: python

dist: trusty

python:
  - "2.7"

# command to install
install:
  - pip install codecov
  - python setup.py install

addons:
  sonarcloud:
    organization: "Jeremiah Leary"

# command to run tests
script:
  - coverage run setup.py test
  - sonar-scanner

after_success:
  - codecov
